AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Twitter::Account::Follow resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: twitter_account_tweet.handlers.resource
      Runtime: python3.7
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: twitter_account_tweet.handlers.test_entrypoint
      Runtime: python3.7
      CodeUri: build/

